# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TuyaSmartNFC' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  
  # Pods for TuyaSmartNFC
  pod 'TuyaSmartUtil', :path => '../TuyaSmartSDK/TuyaSmartUtil'
  pod 'TuyaSmartBaseKit', :path => '../TuyaSmartSDK/TuyaSmartBaseKit'
  pod 'TuyaSmartDeviceKit', :path => '../TuyaSmartSDK/TuyaSmartDeviceKit'
  pod 'TuyaSmartDeviceCoreKit', :path => '../TuyaSmartSDK/TuyaSmartDeviceCoreKit'
  pod 'TuyaSmartMQTTChannelKit', :path => '../TuyaSmartSDK/TuyaSmartMQTTChannelKit'
  pod 'TuyaSmartSocketChannelKit', :path => '../TuyaSmartSDK/TuyaSmartSocketChannelKit'
  pod 'TuyaSmartActivatorKit', :path => '../TuyaSmartSDK/TuyaSmartActivatorKit'
  pod 'TuyaSmartActivatorCoreKit', :path => '../TuyaSmartSDK/TuyaSmartActivatorCoreKit'
  pod 'TuyaSmartBLEKit', :path => '../TuyaSmartSDK/TuyaSmartBLEKit'
  pod 'TuyaSmartBLEMeshKit', :path => '../TuyaSmartSDK/TuyaSmartBLEMeshKit'
  pod 'TuyaSmartSceneKit', :path => '../TuyaSmartSDK/TuyaSmartSceneKit'
  pod 'TuyaSmartTimerKit', :path => '../TuyaSmartSDK/TuyaSmartTimerKit'
  pod 'TuyaSmartMessageKit', :path => '../TuyaSmartSDK/TuyaSmartMessageKit'
  pod 'TuyaSmartFeedbackKit', :path => '../TuyaSmartSDK/TuyaSmartFeedbackKit'
  pod 'TYBluetooth', :path => '../TuyaSmartSDK/TYBluetooth'
  
  pod 'Toast-Swift'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
    end
  end
end
